kind: pipeline
type: docker
name: go
        
steps:
  
  - name: fetch git submodules
    image: node:14-alpine
    commands:
      - apk add git
      - git submodule init
      - git submodule update --recursive --remote
      - git fetch --tags
    when:
      repo:
        - marley77/lemmy-ui

  - name: docker
    image: plugins/docker
    settings:
      repo: marley77/lemmy-ui
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      repo:
        - marley77/lemmy-ui

