name: docker

on:
  push:
  # schedule:
  # - cron: "22 2 * * 1"
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Set up QEMU
    #  uses: docker/setup-qemu-action@v1

    # - name: Update submodules
    #  run: git submodule update --init --recursive
      
    # - name: Buildx
    #  uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}     

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        # platforms: linux/amd64,linux/arm64/v8
        # platforms: linux/arm64/v8
        platforms: linux/arm64
        push: true
        tags: qz77/ui2:latest
